### ISSUE TITLE
Requiring from Repl Throwing

### ISSUE THREAD

**Issue by vinnie-pepi** [chenguo/franca-js#1]
Hey Chen, can you try to just npm install in a directory, and require franca-js.  I was just testing it out and it threw on me. Thanks.

**Comment by chen-factual** [comment]
Hey can you give me a stack trace? I had some issue with app-root-path,
latest version should have resolved that. If it's something else lll
prioritize fixing it asap

**Comment by vinnie-pepi** [comment]
yeah, it was an app-root-path. I actually saw that you were fixing it
yesterday, but maybe you hadn't pushed the fix to npm yet? I'll pull down a
new version from npm and try it later. Cheers.

On Sun, Jan 3, 2016 at 5:58 AM, Chen Guo notifications@github.com wrote:

> Hey can you give me a stack trace? I had some issue with app-root-path,
> latest version should have resolved that. If it's something else lll
> prioritize fixing it asap
> On Jan 1, 2016 04:54, "vinnie-pepi" notifications@github.com wrote:
> 
> > Hey Chen, can you try to just npm install in a directory, and require
> > franca-js. I was just testing it out and it threw on me. Thanks.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/chenguo/franca-js/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chenguo/franca-js/issues/1#issuecomment-168431074.

## 

_Factual Confidential Information_
This email contains Factual confidential information and is only for use by
the intended recipient under the terms of a non-disclosure agreement or
other binding confidentiality terms.  If you've gotten this email in error,
please let the sender know of the mistake and delete the email
immediately.

**Comment by vinnie-pepi** [comment]
just tried removing and reinstalling to see if I had the latest

```
Error: Cannot find module 'app-root-path'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365
```

**Comment by chenguo** [comment]
Are you trying to run tests? app-root-path is only used in tests now. I'll
take out app-root-path completely, it's only been problems.

**Comment by vinnie-pepi** [comment]
Yeah, I'm just testing it out.

On Sun, Jan 3, 2016 at 12:56 PM, Chen Guo notifications@github.com wrote:

> Are you trying to run tests? app-root-path is only used in tests now. I'll
> take out app-root-path completely, it's only been problems.
> 
> On Sat, Jan 2, 2016 at 8:38 PM, vinnie-pepi notifications@github.com
> wrote:
> 
> > just tried removing and reinstalling to see if I had the latest
> > 
> > Error: Cannot find module 'app-root-path'
> > at Function.Module._resolveFilename (module.js:336:15)
> > at Function.Module._load (module.js:278:25)
> > at Module.require (module.js:365
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/chenguo/franca-js/issues/1#issuecomment-168458297.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chenguo/franca-js/issues/1#issuecomment-168462247.

## 

_Factual Confidential Information_
This email contains Factual confidential information and is only for use by
the intended recipient under the terms of a non-disclosure agreement or
other binding confidentiality terms.  If you've gotten this email in error,
please let the sender know of the mistake and delete the email
immediately.

**Comment by vinnie-pepi** [comment]
Does it support a query like SELECT \* FROM [table]?

On Sun, Jan 3, 2016 at 12:58 PM, Vinnie Pepi vinnie@factual.com wrote:

> Yeah, I'm just testing it out.
> 
> On Sun, Jan 3, 2016 at 12:56 PM, Chen Guo notifications@github.com
> wrote:
> 
> > Are you trying to run tests? app-root-path is only used in tests now. I'll
> > take out app-root-path completely, it's only been problems.
> > 
> > On Sat, Jan 2, 2016 at 8:38 PM, vinnie-pepi notifications@github.com
> > wrote:
> > 
> > > just tried removing and reinstalling to see if I had the latest
> > > 
> > > Error: Cannot find module 'app-root-path'
> > > at Function.Module._resolveFilename (module.js:336:15)
> > > at Function.Module._load (module.js:278:25)
> > > at Module.require (module.js:365
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/chenguo/franca-js/issues/1#issuecomment-168458297.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/chenguo/franca-js/issues/1#issuecomment-168462247.
> 
> ## 
> 
> _Factual Confidential Information_
> This email contains Factual confidential information and is only for use
> by the intended recipient under the terms of a non-disclosure agreement or
> other binding confidentiality terms.  If you've gotten this email in error,
> please let the sender know of the mistake and delete the email
> immediately.

## 

_Factual Confidential Information_
This email contains Factual confidential information and is only for use by
the intended recipient under the terms of a non-disclosure agreement or
other binding confidentiality terms.  If you've gotten this email in error,
please let the sender know of the mistake and delete the email
immediately.

**Comment by chen-factual** [comment]
Are you running grunt tests after having NPM installed it or in a git repo? I've found in the git repo it's fine, but with the NPM install is where grunt test throws the app-root-path error.

I'm in the process of removing app-root-path from tests too, but in the short term maybe you can try checking it out as a git-repo and then doing npm install; app-root-path is a devDependency and should be installed.

And yes, it does support Postgres queries. As necessary I should be able to expand to other SQL syntaxes easily. See [this](https://github.com/chenguo/franca-js/blob/master/docs/query-sql.md#sql-table)

**Comment by chen-factual** [comment]
Here's an actual example: https://github.com/Factual/fetch/blob/master/core/examples/postgres.coffee

You'll need your Factual login to see it.

**Comment by chen-factual** [comment]
Version 0.4.4 pushed to npm, with app-root-path removed for now.

**Comment by vinnie-pepi** [comment]
works now, thanks. (no not grunt, I was just trying to use it on the repl)

On Sun, Jan 3, 2016 at 1:13 PM, Chen Guo notifications@github.com wrote:

> Version 0.4.4 pushed to npm, with app-root-path removed for now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chenguo/franca-js/issues/1#issuecomment-168462649.

## 

_Factual Confidential Information_
This email contains Factual confidential information and is only for use by
the intended recipient under the terms of a non-disclosure agreement or
other binding confidentiality terms.  If you've gotten this email in error,
please let the sender know of the mistake and delete the email
immediately.
